import type { Block } from './docx.js';

/** Built-in DOCX templates. Tags: see documents/service.ts templateData(). */
export const TEMPLATES: Record<string, { name: string; blocks: Block[] }> = {
  p1_verification_note: {
    name: 'Notă de verificare a cererii',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Nr. înregistrare: {registration_in}     Data: {today}', align: 'right' },
      { p: 'NOTĂ DE VERIFICARE', bold: true, size: 28, align: 'center', spaceAfter: 60 },
      { p: 'a cererii de {request_type} nr. {request_no} din {submitted_at}', align: 'center', spaceAfter: 240 },
      { p: '**Beneficiar:** {beneficiary_name} (CUI {beneficiary_cui})' },
      { p: '**Proiect:** {project_title}, cod SMIS {smis_code}' },
      { p: '**Contract de finanțare:** nr. {contract_number} din {contract_date}; valoare eligibilă {eligible_value} lei' },
      { p: '**Cont IBAN beneficiar:** {beneficiary_iban}', spaceAfter: 240 },
      { p: '1. Cheltuieli verificate', bold: true },
      {
        table: {
          header: ['Nr.', 'Linie bugetară', 'Document justificativ', 'Solicitat (lei)', 'Eligibil (lei)', 'Neeligibil (lei)', 'Motiv'],
          row: ['{nr}', '{budget_line}', '{document_ref}', '{requested}', '{eligible}', '{non_eligible}', '{reason}'],
          loop: 'expenses',
          widths: [600, 1300, 1900, 1350, 1350, 1350, 1750],
        },
      },
      { p: '**Total solicitat:** {total_requested} lei     **Total eligibil:** {total_eligible} lei', spaceAfter: 240 },
      { p: '2. Lista de verificare', bold: true },
      {
        table: {
          header: ['Nr.', 'Întrebare', 'Răspuns', 'Observații'],
          row: ['{code}', '{question}', '{answer}', '{observation}'],
          loop: 'checklist',
          widths: [600, 5400, 1200, 2400],
        },
      },
      { p: '3. Constatări', bold: true },
      { p: '{findings}', spaceAfter: 360 },
      { p: '**Întocmit:** expert verificare financiară {people.evf_check.name}' },
      { p: '**Avizat:** șef serviciu' },
      { p: '**Aprobat:** director' },
      { p: 'Semnăturile electronice ale persoanelor de mai sus sunt aplicate pe document.', size: 18 },
    ],
  },
  p1_clarification_letter: {
    name: 'Scrisoare de solicitare clarificări',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Către: {beneficiary_name}', spaceAfter: 60 },
      { p: 'Referitor la: cererea nr. {request_no}, proiect cod SMIS {smis_code}', spaceAfter: 240 },
      { p: 'Stimată doamnă / Stimate domn,', spaceAfter: 120 },
      {
        p: 'În urma verificării cererii menționate, vă rugăm să transmiteți, prin MySMIS2021, următoarele clarificări și documente:',
        align: 'both',
      },
      { p: '{clarification_questions}', spaceAfter: 240 },
      { p: 'Termenul de verificare a cererii se suspendă până la primirea răspunsului.', align: 'both', spaceAfter: 360 },
      { p: 'Cu stimă,' },
      { p: '{people.evf_check.name}' },
    ],
  },
  p1_authorization_notice: {
    name: 'Notificare de autorizare la plată',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Către: {beneficiary_name} (CUI {beneficiary_cui})', spaceAfter: 240 },
      { p: 'NOTIFICARE', bold: true, size: 28, align: 'center' },
      { p: 'privind autorizarea cererii de {request_type} nr. {request_no}', align: 'center', spaceAfter: 240 },
      {
        p: 'Vă informăm că, pentru proiectul cod SMIS {smis_code} – {project_title}, din suma solicitată de {total_requested} lei a fost autorizată la plată suma de {total_eligible} lei.',
        align: 'both',
      },
      { p: 'Detalierea pe linii bugetare se regăsește în nota de verificare.', spaceAfter: 360 },
      { p: 'Director' },
    ],
  },
  p2_procurement_note: {
    name: 'Notă de verificare a achiziției',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Nr. înregistrare: {registration_in}     Data: {today}', align: 'right' },
      { p: 'NOTĂ DE VERIFICARE A DOSARULUI DE ACHIZIȚIE', bold: true, size: 26, align: 'center', spaceAfter: 240 },
      { p: '**Beneficiar:** {beneficiary_name}, proiect cod SMIS {smis_code}' },
      { p: '**Obiectul achiziției:** {procurement_object}' },
      { p: '**Procedura:** {procedure_type}; **valoare:** {contract_value} lei; **contractant:** {supplier_name} ({supplier_cui})', spaceAfter: 240 },
      {
        table: {
          header: ['Nr.', 'Verificare', 'Temei', 'Rezultat', 'Observații'],
          row: ['{code}', '{question}', '{legal_basis}', '{answer}', '{observation}'],
          loop: 'checklist',
          widths: [500, 4200, 1500, 1200, 2200],
        },
      },
      { p: '**Constatări:** {findings}' },
      { p: '**Aviz:** {verdict}; reducere propusă: {correction_percent}% ({correction_amount} lei)', spaceAfter: 360 },
      { p: '**Întocmit:** {people.procurement_check.name}' },
      { p: '**Avizat:** șef serviciu' },
      { p: '**Aprobat:** director' },
    ],
  },
  p3_analysis_note: {
    name: 'Notă de analiză a solicitării de modificare',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Nr. înregistrare: {registration_in}     Data: {today}', align: 'right' },
      { p: 'NOTĂ DE ANALIZĂ', bold: true, size: 28, align: 'center', spaceAfter: 60 },
      { p: 'privind solicitarea nr. {request_no} din {request_date} ({kind})', align: 'center', spaceAfter: 240 },
      { p: '**Beneficiar:** {beneficiary.name} · **Proiect:** cod SMIS {smis_code}, contract {contract_number}' },
      { p: '**Situația actuală:** finalizare la {current_end_date}; valoare eligibilă {current_eligible_value} lei' },
      { p: '**Modificări solicitate:** {changes}' },
      { p: '**Situația propusă:** finalizare la {new_end_date}; valoare eligibilă {new_eligible_value} lei', spaceAfter: 240 },
      { p: 'Analiza expertului', bold: true },
      { p: '{analysis}', align: 'both' },
      { p: '**Aviz juridic:** {legal_opinion}' },
      { p: '**Propunere:** {decision}', spaceAfter: 360 },
      { p: '**Întocmit:** {people.analysis.name}' },
      { p: '**Avizat:** șef serviciu' },
      { p: '**Aprobat:** director' },
    ],
  },
  p3_addendum: {
    name: 'Act adițional / notificare la contractul de finanțare',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: '{kind}', bold: true, size: 28, align: 'center', spaceAfter: 60 },
      { p: 'la contractul de finanțare nr. {contract_number}, proiect cod SMIS {smis_code}', align: 'center', spaceAfter: 240 },
      { p: 'Încheiat între {organization.name}, în calitate de autoritate de management / organism intermediar, și {beneficiary.name} (CUI {beneficiary.cui}), în calitate de beneficiar.', align: 'both' },
      { p: '**Art. 1.** Se aprobă următoarele modificări: {changes}', align: 'both' },
      { p: '**Art. 2.** Data de finalizare a proiectului devine {new_end_date}. Valoarea eligibilă devine {new_eligible_value} lei (acolo unde se modifică).', align: 'both' },
      { p: '**Art. 3.** Celelalte prevederi ale contractului rămân neschimbate.', align: 'both', spaceAfter: 360 },
      { p: 'Director' },
    ],
  },
  p4_finding_report: {
    name: 'Proces-verbal de constatare a neregulii',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Data: {today}', align: 'right' },
      { p: 'PROCES-VERBAL DE CONSTATARE', bold: true, size: 28, align: 'center', spaceAfter: 60 },
      { p: 'a neregulilor și de stabilire a creanțelor bugetare', align: 'center', spaceAfter: 240 },
      { p: '**Beneficiar:** {beneficiary_name} (CUI {beneficiary.cui}) · **Proiect:** cod SMIS {smis_code}' },
      { p: '**Sursa sesizării:** {source}' },
      { p: '**Descrierea suspiciunii:** {suspicion}', align: 'both' },
      { p: '**Tipul neregulii:** {irregularity_type} · **Rezultat:** {outcome}' },
      { p: 'Constatări', bold: true },
      { p: '{finding}', align: 'both' },
      { p: '**Temei legal:** {legal_basis}' },
      { p: '**Creanța bugetară stabilită:** {debt_principal} lei, scadentă la {debt_due_date}' },
      { p: '**Raportare IMS (OLAF):** {ims_report}', spaceAfter: 360 },
      { p: '**Echipa de control:** {people.assessment.name}' },
      { p: '**Avizat:** șef serviciu nereguli' },
      { p: '**Aprobat:** director' },
    ],
  },
  p4_debt_title: {
    name: 'Titlu de creanță',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'TITLU DE CREANȚĂ', bold: true, size: 28, align: 'center', spaceAfter: 240 },
      { p: 'Prin prezentul titlu de creanță se stabilește în sarcina {beneficiary_name} (CUI {beneficiary.cui}), beneficiar al proiectului cod SMIS {smis_code}, o creanță bugetară în cuantum de **{debt_principal} lei**, rezultată din procesul-verbal de constatare a neregulilor.', align: 'both' },
      { p: 'Suma se achită până la data de **{debt_due_date}**. Pentru neplata la termen se datorează dobânzi și penalități conform legii.', align: 'both' },
      { p: 'Împotriva prezentului titlu se poate formula contestație în condițiile legii (OUG 66/2011).', align: 'both', spaceAfter: 360 },
      { p: 'Director' },
    ],
  },
  p6_necessity_report: {
    name: 'Referat de necesitate',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Nr. {raw.reg_necessity_reports_internal}     Data: {today}', align: 'right' },
      { p: 'REFERAT DE NECESITATE', bold: true, size: 28, align: 'center', spaceAfter: 240 },
      { p: '**Obiect:** {purpose}' },
      { p: '**Necesitate și oportunitate:** {justification}', align: 'both' },
      { p: '**Sursa de finanțare:** {funding_source} · **Indicator bugetar:** {budget_line}', spaceAfter: 120 },
      {
        table: {
          header: ['Nr.', 'Denumire', 'Cant.', 'Preț unitar', 'TVA %', 'Fără TVA', 'TVA', 'Total'],
          row: ['{nr}', '{description}', '{quantity}', '{unit_price}', '{vat_rate}', '{net}', '{vat}', '{gross}'],
          loop: 'items',
          widths: [500, 2600, 700, 1200, 700, 1300, 1200, 1400],
        },
      },
      { p: '**Total fără TVA:** {total_net} lei · **TVA:** {total_vat} lei · **Total:** {total} lei', spaceAfter: 360 },
      { p: '**Întocmit:** {people.draft.name}' },
      { p: '**Aprobat:** șef compartiment · **Viza CFPP** · **Ordonator de credite**' },
    ],
  },
  p6_payment_authorization: {
    name: 'Ordonanțare de plată',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'ORDONANȚARE DE PLATĂ', bold: true, size: 28, align: 'center', spaceAfter: 240 },
      { p: '**Referat de necesitate:** nr. {raw.reg_necessity_reports_internal} · **Obiect:** {purpose}' },
      { p: '**Beneficiarul plății:** {supplier_name}, CUI {supplier_cui}, IBAN {supplier_iban}' },
      { p: '**Document justificativ:** factura nr. {invoice_no} din {invoice_date}, în valoare de {invoice_amount} lei' },
      { p: '**Recepție:** {reception_note}' },
      { p: '**Indicator bugetar:** {budget_line} · **Sursa de finanțare:** {funding_source}', spaceAfter: 240 },
      { p: 'Se ordonanțează la plată suma de **{invoice_amount} lei**.', spaceAfter: 360 },
      { p: '**Compartiment financiar-contabil:** {people.authorization.name}' },
      { p: '**Viza CFPP** · **Ordonator de credite**' },
    ],
  },
  p7_decision: {
    name: 'Decizie',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'DECIZIA nr. {raw.reg_decisions_internal}', bold: true, size: 28, align: 'center', spaceAfter: 60 },
      { p: 'privind {decision_subject}', align: 'center', spaceAfter: 240 },
      { p: 'Directorul {organization.name},', align: 'both' },
      { p: '{legal_basis}', align: 'both' },
      { p: 'DECIDE:', bold: true, align: 'center' },
      { p: '{articles}', align: 'both' },
      { p: 'Prezenta decizie intră în vigoare la data de {effective_date} și se comunică: {recipients}.', align: 'both', spaceAfter: 360 },
      { p: 'Director' },
      { p: 'Avizat pentru legalitate: {people.legal_review.name}', size: 18 },
    ],
  },
  p8_visit_notice: {
    name: 'Notificare privind vizita la fața locului',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Data: {today}', align: 'right' },
      { p: 'Către: {beneficiary_name}', spaceAfter: 60 },
      { p: 'Referitor la: proiectul {project_title}, cod SMIS {smis_code}', spaceAfter: 240 },
      { p: 'NOTIFICARE', bold: true, size: 28, align: 'center' },
      { p: 'privind efectuarea unei verificări la fața locului', align: 'center', spaceAfter: 240 },
      {
        p: 'Vă informăm că în data de **{planned_date}** reprezentanții autorității de management vor efectua o verificare la fața locului, la adresa: {location}.',
        align: 'both',
      },
      {
        p: 'Vă rugăm să asigurați prezența unui reprezentant împuternicit, accesul la bunurile, lucrările și locurile de desfășurare a activităților proiectului, precum și disponibilitatea documentelor originale (contracte, facturi, procese-verbale de recepție, evidența contabilă a proiectului).',
        align: 'both',
      },
      { p: 'Persoană de contact indicată: {beneficiary_contact}.', spaceAfter: 360 },
      { p: 'Cu stimă,' },
      { p: '{people.planning.name}' },
    ],
  },
  p8_visit_report: {
    name: 'Raport de verificare la fața locului',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Nr. {raw.reg_onsite_visits_internal}     Data: {today}', align: 'right' },
      { p: 'RAPORT DE VERIFICARE LA FAȚA LOCULUI', bold: true, size: 28, align: 'center', spaceAfter: 240 },
      { p: '**Beneficiar:** {beneficiary_name} (CUI {beneficiary.cui})' },
      { p: '**Proiect:** {project_title}, cod SMIS {smis_code}' },
      { p: '**Motivul vizitei:** {visit_reason} · **Cererea / dosarul verificat:** {sampled_reference}' },
      { p: '**Locul verificării:** {location}' },
      { p: '**Data vizitei:** {visit_date} · **Reprezentantul beneficiarului:** {representative}, {representative_role}', spaceAfter: 240 },
      { p: '1. Lista de verificare', bold: true },
      {
        table: {
          header: ['Nr.', 'Verificare', 'Răspuns', 'Observații'],
          row: ['{code}', '{question}', '{answer}', '{observation}'],
          loop: 'checklist',
          widths: [600, 5400, 1200, 2400],
        },
      },
      { p: '2. Constatări', bold: true },
      { p: '{findings}', align: 'both' },
      { p: '3. Rezultat: {result}', bold: true },
      { p: '**Recomandări:** {recommendations}', align: 'both' },
      { p: '**Termen de implementare:** {recommendations_deadline}', spaceAfter: 240 },
      { p: 'Fotografiile realizate în timpul vizitei (cu data, ora și poziția GPS) și semnătura reprezentantului beneficiarului sunt anexate la prezentul raport.', align: 'both', spaceAfter: 360 },
      { p: '**Verificare efectuată de:** {people.visit.name}' },
      { p: '**Avizat:** șef serviciu · **Aprobat:** director' },
    ],
  },
  p5_reply_letter: {
    name: 'Răspuns la corespondență',
    blocks: [
      { p: '{organization.name}', bold: true },
      { p: 'Către: {sender_name}', spaceAfter: 60 },
      { p: 'Referitor la: {subject} (înregistrat cu nr. {registration_in})', spaceAfter: 240 },
      { p: '{reply_summary}', align: 'both', spaceAfter: 360 },
      { p: 'Cu stimă,' },
      { p: 'Semnat electronic' },
    ],
  },
};
